name: project3
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pandas>=1.1
  - numpy>=1.18
  - opencv
  - seaborn
  - scikit-learn
  - theano
  - pillow
  - ipykernel
  - jupyter
  - pip:
      - pip
      - matplotlib
      - keras
      - piexif